// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.DomainandIPPinger
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("host")]
        public string Host { get; set; }

        [JsonProperty("numericHost")]
        public string NumericHost { get; set; }

        [JsonProperty("alive")]
        public bool Alive { get; set; }

        [JsonProperty("roundTrips")]
        public long RoundTrips { get; set; }

        [JsonProperty("packetLoss")]
        public long PacketLoss { get; set; }

        [JsonProperty("minMS")]
        public double MinMs { get; set; }

        [JsonProperty("avgMS")]
        public double AvgMs { get; set; }

        [JsonProperty("maxMS")]
        public double MaxMs { get; set; }

        [JsonProperty("stdDev")]
        public double StdDev { get; set; }

        [JsonProperty("times")]
        public double[] Times { get; set; }
    }
}
